name: "JS Linter"
on: push
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: add eslint
      - uses: bradennapier/eslint-plus-action@v3.4.2
        with:
          reportIgnoredFiles: true
          issueSummaryOnlyOnEvent: true
          extensions: "['.js']"
